title: PUNIT
author: PUNIT SHARMA
email: PUNITSHARMA.8022@GMAIL.COM
description: > # this means to ignore newlines until "show_exerpts:"
 hi it's PUNIT
 Welcome to my personal space on the web! I created this site to share my achievements, 
 showcase my projects, and post updates about my journey through life, tech, and everything in between.
 Thanks for stopping by—feel free to explore!


show_excerpts: false # set to true to show excerpts on the homepage

paginate: 3
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://x.com/punit_247
      icon: twitter-square
      color: cyan
    - url: https://punit247.itch.io/
      icon: itch-io
      color: red
    - url: https://github.com/beastinvains
      icon: github-square
      color: purple
    - url: https://www.instagram.com/punit_bytes/
      icon: instagram
      color: pink
    - url: https://www.linkedin.com/in/punit-sharma-68b49425a/    
      icon: linkedin-square
      color: blue
    - url: https://www.youtube.com/@DarkFablesoffical
      icon: youtube
      color: red
    - url: https://www.pinterest.com/punitsharma8022/
      icon: pinterest
      color: pink
    - url: https://www.reddit.com/user/Ill-Journalist6540/
      icon: reddit
      color: orange
    - url: https://www.snapchat.com/punit_shar8022
      icon: snapchat
      color: yellow

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  #avatar_source: github
  #github_username: bitbrain
  #avatar_source: local
  avatar_path: assets/avatar.png

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
 
